---
# tasks file for deprovision-zcee
- name: Create tempdir
  tempfile:
    state: directory
  register: tmp_file

- name: Deprovision zCEE 
  block:

    # * Need this because Ansible lazily interprets role_path
    # * Results in wrong paths being sent when passing vars that use role_path var
    - set_fact:
        eager_role_path: '{{role_path}}'

    - include_role: 
        name: send-template
      vars:
        path: '{{ eager_role_path }}/templates/deprovision/STOPZCEE.j2'

    - name: Stop zCEE server job
      submit_jcl:
        name: STOPZCEE.j2
        path: '{{ uss_file_path }}'

    - name: Stop zCEE server from USS
      shell: ./zosconnect stop {{softwareServiceInstanceName}}
      args:
        chdir: '{{ ZCON_INSTALL_DIR }}/bin'
      environment:
        WLP_USER_DIR: '{{ZCON_ZFS_MOUNTPOINT}}/{{softwareServiceInstanceName}}'
      ignore_errors: yes

    - name: Delete existing directory if necessary
      file:
        path: '{{ZCON_ZFS_MOUNTPOINT}}/{{softwareServiceInstanceName}}' #/servers/{{softwareServiceInstanceName}}'
        state: absent 

  always:
    - name: Delete the temporary folder
      file:
        path: "{{ tmp_file.path }}"
        state: absent
      when: tmp_file
  vars:
    TEMP_DIR: '{{ tmp_file.path }}'