- name: Configure Bank of Z
  hosts: zsystem
  gather_facts: false
  # * Include different variable files depending on environment/inventory used
  vars_files:
    - "{{ vars_folder_name }}/ims-dbdc.yml" # TODO: reorganize variable heirarchy where possible
    - "{{ vars_folder_name }}/bank.yml"
  environment: '{{ system_environment }}'

  tasks:
    - name: Create temporary directory to store bank files
      tempfile:
        state: directory
      register: bank_tmp_dir

    - block: 

        - include_role: 
            name: install-bzip2

        - include_role: 
            name: install-mvs-utilities

        - include_role:
            name: configure-ims-bank

      always:
        - name: Delete the temporary directory
          file:
            path: "{{ bank_tmp_dir }}"
            state: absent
      vars:
        uss_file_path: '{{ bank_tmp_dir.path }}'
