- name: Create inventory for provisioned instance
  hosts: localhost
  gather_facts: false
  vars_files:
    - "group_vars/zsystem.yml"
    - "vars/create-inventory.yml"
  environment:
    ANSIBLE_SSH_PIPELINING: 0

  tasks:
    - set_fact:
      instance_datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

    - name: Add Tower inventory 
      tower_inventory:
        name: "{{ instance_name }}_instance_{{ instance_datetime }}"
        organization: '{{ instance_org | default("Default")}}'
        variables: '{{ instance_vars }}'
        tower_username: '{{ tower_username }}'
        tower_password: '{{ tower_password }}'
        state: present
        
    # - name: Get organization ID 
    #   block:
    #     - uri:
    #         url: '{{ tower_url }}/api/v2/organizations/?search={{ instance_org }}'
    #         method: GET
    #         user: '{{ tower_username }}'
    #         password: '{{ tower_password }}'
    #         force_basic_auth: yes
    #         status_code: 200
    #       register: organizations
    #     - set_fact: 
    #         organization_id: '{{ organizations.results[0].id }}'
    #   rescue:
    #     - debug:
    #         msg: "Specified organization not found , setting to default ID of 1."
    #     - set_fact: 
    #         organization_id: 1
    #   when: instance_org is defined and instance_org != ''



    # - name: Call API to create new inventory
    #   uri:
    #     url: '{{ tower_url }}/api/v2/inventories/'
    #     method: POST
    #     body_format: json
    #     user: '{{ tower_username }}'
    #     password: '{{ tower_password }}'
    #     force_basic_auth: yes
    #     body:
    #       name: "{{ instance_name }}_instance_{{ instance_datetime }}"
    #       description: Inventory for provisioned instance
    #       organization: '{{ organization_id | default(1)}}'
    #       variables: '{{ instance_vars | to_json }}'
    #     status_code: 201

    - debug:
        msg: 
          - "An Ansible Tower instance has been created for your provisioned instance."
          - "The instance name is: {{ instance_name }}_instance_{{ instance_datetime }}"
