- name: Deploy tools used during middleware provisioning
  hosts: zsystem
  gather_facts: false
  vars_files:
  environment: '{{ system_environment }}'

  tasks:
    - name: Create temporary directory to store provisioning files
      tempfile:
        state: directory
      register: provision_tmp_dir
      
    - set_stats:
        data:
          uss_file_path: '{{ provision_tmp_dir.path }}' 
          uss_utilities_path: '{{ provision_tmp_dir.path }}' 

    - block:
    
        - include_role: 
            name: install-bzip2

        - include_role: 
            name: install-mvs-utilities

      # always:
      #   - name: Delete the temporary provision files directory
      #     file:
      #       path: "{{ provision_tmp_dir.path }}"
      #       state: absent
