- name: Downloads and installs Python 3.6 from artifactory
  hosts: zsystem
  environment: '{{ system_environment }}'


  tasks:
    - include_role:
        name: deploy-python36-from-artifactory

# ansible-playbook -i inventories/zvm install-python.yml