- name: Provision IMS DB/DC
  hosts: zsystem
  gather_facts: false
  # * Include different variable files depending on environment/inventory used
  vars_files:
    - "{{ vars_folder_name }}/ims-dbdc.yml"
  environment: '{{ system_environment }}'

  tasks:
    - name: Create temporary directory to store provisioning files
      tempfile:
        state: directory
      register: provision_tmp_dir
      tags:
       - always

    - block:
      - block:
          - include_role: 
              name: install-bzip2

          - include_role: 
              name: provision-ims-dbdc
              tasks_from: create_ims
        tags:
        - create_ims

      - block:
          - include_role: 
              name: provision-ims-dbdc
              tasks_from: prep_ims
        tags:
        - prep_ims 

      - block:
          - include_role: 
              name: provision-ims-dbdc
              tasks_from: start_ims
        tags:
        - start_ims

      always:
        - name: Delete the temporary provision files directory
          file:
            path: "{{ provision_tmp_dir.path }}"
            state: absent
      tags:
       - always
      vars:
        uss_file_path: '{{ provision_tmp_dir.path }}'
        
