- name: Provision IMS Bank and dependencies
  hosts: z-system
  gather_facts: false
  vars_files:
    - "vars/ims-dbdc.yml"
    - "vars/bank.yml"

  environment:
   # environment variables for python
    INSTALL_PYTHON: /var/python27
    RELEASE_NAME: python-2017-04-12
    RELEASE_TYPE: py27
    RELEASE_DIR: /var/python27/python-2017-04-12-py27
    PKGS_BASE: /var/python27/python-2017-04-12-py27/pkgs
    PYTHON_ENV: python27
    PYTHON_HOME: /var/python27/python-2017-04-12-py27/python27
    PYTHON: /var/python27/python-2017-04-12-py27/python27/bin
    LIBPATH: /var/python27/python-2017-04-12-py27/python27/lib:${LIBPATH}
    FFI_LIB: /var/python27/python-2017-04-12-py27/python27/lib/ffi
    TERMINFO: /var/python27/python-2017-04-12-py27/python27/share/terminfo
    PKG_CONFIG_PATH: /var/python27/python-2017-04-12-py27/python27/share/pkgconfig:/var/python27/python-2017-04-12-py27/python27/lib/pkgconfig
    CURL_CA_BUNDLE: /var/python27/python-2017-04-12-py27/python27/etc/ssl/cacert.pem
    # environment variables for mvsutils/mvscmd
    _: /hsstools/bin/env
    _BPXK_AUTOCVT: ON
    _CEE_RUNOPTS: 'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'
    _TAG_REDIR_ERR: txt
    _TAG_REDIR_IN: txt
    _TAG_REDIR_OUT: txt
    TOOLS_ROOT: /hsstools
    GIT_SHELL=: /hsstools/bin/bash
    GIT_EXEC_PATH: /hsstools/git-2.14.4/libexec/git-core
    GIT_TEMPLATE_DIR: /hsstools/git-2.14.4/share/git-core/templates
   # Java environment
    JAVA_HOME: /usr/lpp/java/J8.0_64

  tasks:
    - name: Release a TCPIP port
      zport:
        state: closed
        port: '{{ item }}'
      loop: 
        - 1300
        - 1301
        - 1302
        - 1303
        - 1304
        - 1305
        - 1306
        - 1307
