---
# defaults file for deprovision-ims-dbdc

# the path where JCL and other scripts will be stored
uss_file_path: /tmp
# the path where additional utilities are located
uss_utilities_path: /tmp

# DFS_ENVIRONMENT: DEV
# DFS_IMS_SECURITY:

# These next values are only used for deprovisioning
# need to create jmps and mpps using separate playbooks
HAS_MPPS: yes
NUM_OF_MPPS: 2
HAS_JMPS: yes
NUM_OF_JMPS: 1
DFS_INIT_JAVA_CONF: true

DFS_IMS_UNIT: SYSALLDA
DFS_IMS_UNIT2: 3390
DFS_PORTIDSuf: 99
DFS_IMSXCFGroup: IMSXCFGN

DFS_IMS_CRC: '@'
DFS_IMS_LINEGRP: SPOOL

# DFS_MOUNTPOINT: /usr/lpp/ims/ims13/imsjava
# DFS_FSTYPE: HFS

DFS_useRRS: 'N' 

# DFS_VTAM_NODE_IMSMTO: PMASTER1
# DFS_VTAM_NODE_IMSND1: USER0001
# DFS_VTAM_NODE_IMSND2: USER0002

IST_VTAM_IMSAPPLID: '{{ DFS_IMS_SSID }}'
# IST_VTAM_Procedure: VTAM
# EZB_TCPIP_LoadLib: SYS1.TCPIP.LINKLIB
# GIM_IMS_TARGETzone: IMSTZ13
# GIM_IMS_GLOBALzone_CSI: IMSCLOUD

# zCloud_LPALIB: SYS1.LPALIB

zCloud_PROCLIB: USER.PRIVATE.PROCLIB #'{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB'
zCloud_MODGEN: SYS1.MODGEN

# zCloud_VTAM_VTAMLIST: SYS3.VTAMLST
# zCloud_VTAM_VTAMLIB: SYS3.VTAMLIB
# zCloud_VTAM_VOL: IMSCLS
# zCloud_VTAM_DEV: SYSALLDA
# zCloud_IMS_DEV: SYSALLDA
# zCloud_IMSConnect: HWS1

DFS_useIEFJOBS: 'N'
zCloud_IEFJOBS: SYS1.IEFJOBS
DFS_IXUSTIM1: 300

# DFS_IXUSTIM3: 1440

DXR_IRLM_SSID: XRLM
DXR_IRLM_Procedure: IRLM23D

# cobolcomp: DSNAME

CSQ_SSID: CSQ1

## SVC Values
zCloud_IMS_SVC_Type2: '203'  #'229'
zCloud_IMS_SVC_Type4: '202'  #'249'

# the library to send the output of DFSPROCB
ADDTL_SAMP_PROC_LIB: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB'

# any jobs/procs created that should be saved for later use and/or reference 
desired_install_job_save_locations:
  provision:
    - file_name: DFSE302J
      ds_member: IV3E302J
      hlq: INSTALL
    - file_name: DFSALSY1
      ds_member: IV3E101J
      hlq: INSTALL
    - file_name: DFSALCAT
      ds_member: IV3E319J
      hlq: INSTALL
    - file_name: DFSALSY2
      ds_member: IV3C101J
      hlq: INSTALL
    - file_name: DFSSETPG
      ds_member: IV3D201T
      hlq: INSTALL
    - file_name: DFS4CPYP
      ds_member: IV3E312J
      hlq: INSTALL
    - file_name: DFSE313J
      ds_member: IV3E313J
      hlq: INSTALL
    - file_name: DFSCPYST
      ds_member: IV3E318J
      hlq: INSTALL
    - file_name: DFS4ICON
      ds_member: '{{ DFS_IMS_SSID }}HWS1'
      hlq: JOBS
    - file_name: DFSE304J
      ds_member: IV3E304J
      hlq: INSTALL
    - file_name: DFSE303J
      ds_member: IV3E303J
      hlq: INSTALL
    - file_name: DFSDYNAL
      ds_member: IV3E301J
      hlq: INSTALL
    - file_name: DFSENOLC
      ds_member: IV3E317J
      hlq: INSTALL
    - file_name: DFS4ACTV
      ds_member: IV3E318J
      hlq: INSTALL
    - file_name: DFSE305J
      ds_member: IV3E305J
      hlq: INSTALL
    - file_name: DFSGNPRE
      ds_member: IV3C202J
      hlq: INSTALL
    - file_name: DFSLDCAT
      ds_member: IV3E319K
      hlq: INSTALL
    - file_name: DFS4SE3
      ds_member: IV3E203J
      hlq: INSTALL
    - file_name: DFSAPPGN
      ds_member: IV3E201J
      hlq: INSTALL
    - file_name: DFS4APPG
      ds_member: IV3E203J
      hlq: INSTALL
    - file_name: DFSE315J
      ds_member: IV3E315J
      hlq: INSTALL
    - file_name: DFSE314J
      ds_member: IV3E314J
      hlq: INSTALL
    - file_name: DFSC105J
      ds_member: IV3C105J
      hlq: INSTALL
    - file_name: DFS4STG1
      ds_member: IV3C203J
      hlq: INSTALL
    - file_name: DFSDFDRC
      ds_member: IV3E207J
      hlq: INSTALL
    - file_name: STARTCTL
      ds_member: STARTCTL
      hlq: JOBS
    - file_name: STARTOM
      ds_member: STARTOM
      hlq: JOBS
    - file_name: STARTRM
      ds_member: STARTRM
      hlq: JOBS
    - file_name: STARTSCI
      ds_member: STARTSCI
      hlq: JOBS
    - file_name: DFS4DSVC
      ds_member: IV3D209T
      hlq: INSTALL
  deprovision:
    - file_name: DFSUNMNT
      ds_member: UNMOUNT
      hlq: INSTALL