---
# tasks file for load-csv-data
- name: Compile the DB2Import source file
  command: javac DB2Import.java
  args:
    chdir: "{{ playbook_dir }}/roles/load-csv-data/files"
  delegate_to: localhost

- name: Transfer the files
  copy:
    src: "{{ item }}"
    dest: "{{ uss_file_path }}/"
  with_fileglob:
    - "{{ playbook_dir }}/roles/load-csv-data/files/*"

- name: Import from CSV file
  shell: |
    PATH=$PATH:$JAVA_HOME/bin
    java -cp ./:db2jcc.jar:db2jcc_license_cisuz.jar DB2Import {{ DB2_INSTANCE }} {{ DB2_SCHEMA }} {{ DB2_TABLE }} {{ CSV_FILE_PATH }} {{ DB2_USER }} {{ DB2_PASSWORD }} {{ DB2_URL }} {{ DB2_PORT }}
  args:
    chdir: "{{ uss_file_path }}"

- name: Remove the class file
  file:
    path: "{{ playbook_dir }}/roles/load-csv-data/files/DB2Import.class"
    state: absent
  delegate_to: localhost