---
# tasks file for git-clone-private-repo

# * secret_key variable should always be defined when using tower
# * when not using tower, normal agent forwarding should be sufficient
- name: Add SSH key for github repo
  shell: ssh-add {{ secret_key }}
  delegate_to: localhost
  when: secret_key is defined

- name: Remove old repo
  file:
    path: "{{ CLONE_DEST }}"
    state: absent

- name: Clone the repo
  shell: GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git clone {{ GIT_REPO }} {{ CLONE_DEST }}

- name: Checkout correct branch
  shell: git checkout {{ GIT_BRANCH }}
  args:
    chdir: '{{ CLONE_DEST }}'
  when: GIT_BRANCH is defined