---
# tasks file for deploy-frontend-cli
- name: Initial setup
  block:
  - name: Install necessary cli tools
    delegate_to: localhost
    shell: curl -sL https://ibm.biz/idt-installer | bash

  - name: Make a temporary directory
    delegate_to: localhost
    tempfile:
      state: directory
    register: tmp_dir

  - name: Install OpenShift CLI
    delegate_to: localhost
    command: "tar -xJf {{ playbook_dir }}/roles/deploy-frontend-cli/files/openshift-cli.tar.xz -C {{ tmp_dir.path }}"

  - set_fact:
      CLI: "{{ tmp_dir.path }}/openshift-cli"


- name: Deploy the Bank of Z Docker image
  block:
  - name: Login to the Openshift cluster
    delegate_to: localhost
    command: "{{ CLI }}/oc login --token={{ AUTH_TOKEN }} {{ SERVER }}"

  - name: Delete existing app
    delegate_to: localhost
    command: "{{ CLI }}/oc delete all -l app={{ APP_NAME }}" 

  - name: Create new app
    delegate_to: localhost
    command: "{{ CLI }}/oc new-app {{ DOCKER_IMAGE }} --name {{ APP_NAME }}"

  - name: Expose new app to the public
    delegate_to: localhost
    command: "{{ CLI }}/oc expose svc {{ APP_NAME }}"


- name: Clean up
  delegate_to: localhost
  file:
    path: "{{ tmp_dir.path }}"
    state: absent