---
# tasks file for deploy-python36

- name: Create dir to store files
  raw: mkdir -p {{ copy_dir }} {{ '; mkdir -p {0}'.format(install_dir) if install_dir != copy_dir else ''}}

- name: Copy install files to z/OS USS
  shell: "{{ sftp_path }} {{ ansible_user }}@{{ ansible_host }}:{{ copy_dir }} <<< $'put {{ role_path }}/files/{{ python_file_name }}.tar.gz'"
  delegate_to: localhost
​
- name: Decompress python install tar
  raw: '{{ gzip_path }} -d {{ copy_dir }}/{{ python_file_name }}.tar.gz'
  
- name: Untar python install 
  raw: tar -xUXf {{ copy_dir }}/{{ python_file_name }}.tar -Co {{ install_dir }}
​
- name: Run install packages
  raw: >
    export _BPXK_AUTOCVT=ON ;
    export BASH_PREFIX=/usr/lpp/rsusr/ported ; 
    export PERL_PREFIX=/usr/lpp/rsusr/ported ; 
    export RELEASE_NAME={{ python_release_name }} ; 
    export RELEASE_TYPE={{ python_release_type }} ;
    export INSTALL={{ install_dir }} ;
    export RELEASE_DIR=$INSTALL/{{ python_file_name }} ;
    export PKGS_BASE=$RELEASE_DIR/pkgs ;
    {{ install_dir }}/{{ python_file_name }}/python36/bin/install_all_packages