---
# tasks file for check-job-status

- name: Get the logs from the job
  shell: "./pjdd {{ job_id }} jesmsglg"
  retries: 120
  delay: 1
  args:
    chdir: "{{ uss_utilities_path }}"
  register: job_logs
  until: "job_logs.stdout | regex_search(' ENDED ')"


- name: Grab return code
  set_fact:
    new_rc: "{{ job_logs.stdout | regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: 'ENDED\s-\sRC=([0-9]{4})'

- name: Ensure job didn't fail
  assert:
    that:
    - '{{ new_rc | int }} <= {{ max_rc | int}}' 