---
# tasks file for check-acblib
# Check which ACB library is inactive
- name: Step - get-display-modify-log
  include_role:
    name: submit-jcl 
    public: yes
  vars:
    jcl_name: 'CHECKACBLIB.j2'  

- name: Get the logs from the job
  shell: "./pjdd {{ command_result.stdout }} sysprint"
  retries: 2
  delay: 1
  args:
    chdir: "{{ uss_utilities_path }}"
  register: job_logs
  until: "job_logs.stdout | regex_search(' MODIFY COMPLETE ')"

# Grab the inactive acblib
- name: Grab -inactive-acblib
  set_fact:
    INACTIVE_ACBLIB: "{{ job_logs.stdout | regex_search(regexp, '\\1') | first }}"
  vars:
    regexp: '.I.\s\s({{ IMSBANK_HLQ1 }}.{{ IMSBANK_HLQ2 }}.ACBLIB(?:A|B))'
   
- name: output inactive ACBLIB
  debug:
    msg: "Inactive ACBLIB is: {{ INACTIVE_ACBLIB }} "
