---
# defaults file for git-clone-private-repo

# This should always be overridden by higher prescedence variable
TARGET_USERNAME: usrt001

# Git repository to be cloned. Must be SSH (not Https)
GIT_REPO: git@github.ibm.com:IBMZSoftware/nazare-demo-imsapp.git

GIT_BRANCH: ansible-imsbank

# Directory where the repository will be cloned
CLONE_DEST: "/u/{{ TARGET_USERNAME }}/nazare-demo-imsapp"