---
# tasks file for deprovision-ims-dbdc
- name:  Deprovision IMS
  collections:
    - ibm.ibm_zos_core
  block:
    # TODO: add task to search for ports in use by IMS with this SSID and then remove reservation
    # * Need this because Ansible lazily interprets role_path
    # * Results in wrong paths being sent when passing vars that use role_path var
    - set_fact:
        eager_role_path: '{{role_path}}'

    - include_role:
        name: send-templates
      vars:
        template_path: '{{ eager_role_path }}/templates/deprovision/*'

    # - include_role: 
    #     name: save-templates-to-datasets
    #   vars:
    #     datasets: '{{ desired_install_job_save_locations.deprovision }}'

    - name: Stop MPP Regions
      zos_job_submit:
        src: '{{ uss_file_path }}/STOPMPP.j2'
        location: USS
        wait: true
        max_rc: 12
      ignore_errors: yes

    - name: Stop JMP Regions
      zos_job_submit:
        src: '{{ uss_file_path }}/STOPJMP.j2'
        location: USS
        wait: true
        max_rc: 12
      ignore_errors: yes
      
    - block:
        - set_fact:
            ims_up: yes

        - name: wait-for-ims-ready
          include_role:
            name: submit-rexx 
            public: yes
          vars:
            rexx_name: 'WaitJob.j2'
            max_rc: 0
            
      rescue:
        - set_fact:
            ims_up: no

    - name: Stop all IMS resources
      zos_job_submit:
        src: '{{ uss_file_path }}/DFSSTPRS.j2'
        location: USS
        wait: true
        max_rc: 8
      when: ims_up

    - name: Immediate IMS Shutdown
      zos_job_submit:
        src: '{{ uss_file_path }}/DFSISHUT.j2'
        location: USS
        wait: true
        max_rc: 12
      when: ims_up

    - name: Stop ICON
      zos_job_submit:
        src: '{{ uss_file_path }}/DFSSTPIC.j2'
        location: USS
        wait: true
        max_rc: 8


    - name: Stop OM
      zos_job_submit:
        src: '{{ uss_file_path }}/DFSSTPOM.j2'
        location: USS
        wait: true

    - name: Stop RM
      zos_job_submit: 
        src: '{{ uss_file_path }}/DFSSTPRM.j2'
        location: USS
        wait: true

    - name: Stop CSL
      zos_job_submit:
        src: '{{ uss_file_path }}/DFSSTPAS.j2'
        location: USS
        wait: true

    - name: Delete Sysdef libs
      zos_job_submit:
        src: '{{ uss_file_path }}/DFSSYSDL.j2'
        location: USS
        wait: true

    - name: Delete IMS Runtime Libs
      zos_job_submit:
        src: '{{ uss_file_path }}/DFSDELLB.j2'
        location: USS
        wait: true

    - name: Delete IMS Catalog
      zos_job_submit:
        src: '{{ uss_file_path }}/DFSDCTLG.j2'
        location: USS
        wait: true

    - name:  Delete IEFJOBS members
      include_role:
        name: submit-rexx 
        public: yes
      vars:
        rexx_name: 'IEFJOBSX.j2'
        max_rc: 0

    - name: Clean proclib
      zos_job_submit:
        src: '{{ uss_file_path }}/DFSDLMBR.j2'
        location: USS
        wait: true
