---
# tasks file for zcee-deploy
- name: Get list of service project directory
  find:
    paths: "/u/{{ TARGET_USERNAME }}/{{ PROJECT_NAME }}/zCEE/"
    patterns: '*.properties'
    recurse: yes
  register: service_file_list

- name: Generate service archives
  shell: |
    PATH=$PATH:$JAVA_HOME/bin
    {{ ZCEE_BUILD_TOOLKIT_PATH }}/bin/zconbt.zos -pd={{ item.path | dirname }} -f={{ uss_file_path }}/{{ item.path | dirname | basename }}.sar
  with_items:
    - "{{ service_file_list.files }}"

- name: Generate API archives
  shell: |
    PATH=$PATH:$JAVA_HOME/bin
    {{ ZCEE_BUILD_TOOLKIT_PATH }}/bin/zconbt.zos -pd="/u/{{ TARGET_USERNAME }}/{{ PROJECT_NAME }}/zCEE/IMSBankAPI" -f={{ uss_file_path }}/imsbankapi.aar

- name: Copy archives
  shell: |
    rm {{ SERVICE_DEPLOY_PATH }}/*
    rm {{ API_DEPLOY_PATH }}/*
    cp {{ uss_file_path }}/*.sar {{ SERVICE_DEPLOY_PATH }}
    cp {{ uss_file_path }}/*.aar {{ API_DEPLOY_PATH }}
    chmod 777 {{ SERVICE_DEPLOY_PATH }}/*
    chmod 777 {{ API_DEPLOY_PATH }}/*

# - name: Remove service archives
#   file:
#     path: "{{ SERVICE_DEPLOY_PATH }}/{{ item.path | dirname | basename }}.sar"
#     state: absent
#   with_items:
#     - "{{ service_file_list.files }}"

# - name: Remove api archives
#   file:
#     path: "{{ API_DEPLOY_PATH }}/imsbankapi.aar"
#     state: absent

# - name: Copy service archives
#   copy:
#     src: "{{ uss_file_path }}/{{ item.path | dirname | basename }}.sar"
#     dest: "{{ SERVICE_DEPLOY_PATH }}/{{ item.path | dirname | basename }}.sar"
#     remote_src: yes
#   with_items:
#     - "{{ service_file_list.files }}"

# - name: Copy api archives
#   copy:
#     src: "{{ uss_file_path }}/imsbankapi.aar"
#     dest: "{{ API_DEPLOY_PATH }}/imsbankapi.aar"
#     remote_src: yes

# - name: Get list of API project directory
#   find:
#     paths: "/u/{{ TARGET_USERNAME }}/{{ PROJECT_NAME }}/zCEE/"
#     patterns: 'package.xml'
#     recurse: yes
#   register: api_file_list

# - name: List service archives
#   shell: "ls {{ uss_file_path }}/*.sar"
#   register: sar_files

# - name: List API archives
#   shell: "ls {{ uss_file_path }}/*.aar"
#   register: aar_files

# - name: Stop the services
#   uri: 
#     url: "{{ ZCEE_SERVER }}:{{ ZCEE_PORT }}/zosConnect/services/{{ item | basename | regex_replace('.sar', '') }}?status=stopped"
#     validate_certs: no
#     user: "{{ USERNAME }}"
#     password: "{{ PASSWORD }}"
#     force_basic_auth: true
#     method: PUT
#     status_code: 200
#   with_items:
#     - "{{ sar_files.stdout_lines }}"  

# - name: Stop the apis
#   uri: 
#     url: "{{ ZCEE_SERVER }}:{{ ZCEE_PORT }}/zosConnect/apis/imsbankapi?status=stopped"
#     validate_certs: no
#     user: "{{ USERNAME }}"
#     password: "{{ PASSWORD }}"
#     force_basic_auth: true
#     method: PUT
#     status_code: 200

# - name: Delete service archives
#   uri: 
#     url: "{{ ZCEE_SERVER }}:{{ ZCEE_PORT }}/zosConnect/services/{{ item | basename | regex_replace('.sar', '') }}"
#     validate_certs: no
#     user: "{{ USERNAME }}"
#     password: "{{ PASSWORD }}"
#     force_basic_auth: true
#     method: DELETE
#     status_code: 200
#   with_items:
#     - "{{ sar_files.stdout_lines }}"  

# - name: Delete API archives
#   uri: 
#     url: "{{ ZCEE_SERVER }}:{{ ZCEE_PORT }}/zosConnect/apis/imsbankapi"
#     validate_certs: no
#     user: "{{ USERNAME }}"
#     password: "{{ PASSWORD }}"
#     force_basic_auth: true
#     method: DELETE
#     status_code: 200

# - name: Deploy service archives
#   uri: 
#     url: "{{ ZCEE_SERVER }}:{{ ZCEE_PORT }}/zosConnect/services"
#     validate_certs: no
#     user: "{{ USERNAME }}"
#     password: "{{ PASSWORD }}"
#     force_basic_auth: true
#     method: POST
#     src: "{{ item }}"
#     remote_src: yes
#     headers:
#       Content-Type: application/zip
#     status_code: 201
#   with_items:
#     - "{{ sar_files.stdout_lines }}"

# - name: Deploy API archives
#   uri: 
#     url: "{{ ZCEE_SERVER }}:{{ ZCEE_PORT }}/zosConnect/apis"
#     validate_certs: no
#     user: "{{ USERNAME }}"
#     password: "{{ PASSWORD }}"
#     force_basic_auth: true
#     method: POST
#     src: "{{ uss_file_path }}/imsbankapi.aar"
#     remote_src: yes
#     headers:
#       Content-Type: application/zip
#     status_code: 201