---
# tasks file for clean-deprovisioned-instances
- name: Find inventory by name
  block:
    - uri:
        url: '{{ tower_url }}/api/v2/inventories?name={{ inventory_name }}'
        method: GET 
        user: '{{ tower_username }}'
        password: '{{ tower_password }}'
        force_basic_auth: yes
      register: inventory
    - set_fact:
        inventory_id: '{{ inventory.json.results[0].id }}'

  
- name: Get inventory vars holding info about instances
  uri:
    url: '{{ tower_url }}/api/v2/inventories/{{ inventory_id }}/variable_data/'
    method: GET 
    user: '{{ tower_username }}'
    password: '{{ tower_password }}'
    force_basic_auth: yes
  register: variables

- set_fact:
    templates_to_remove: '{{ variables.json.deprovisioned.jobs | default([]) + variables.json.deprovisioned.workflows | default([])}}'

- include_role:
    name: remove-tower-template
  vars:
    workflow_name: '{{ item }}'
  loop: '{{ templates_to_remove }}'
  ignore_errors: yes